import type { ThemeConfig } from 'antd';
import { colors } from '../tokens/colors';
import { typography } from '../tokens/typography';
import { spacing } from '../tokens/spacing';
import { shadows } from '../tokens/shadows';

export const lightTheme: ThemeConfig = {
  token: {
    // Colors
    colorPrimary: colors.primary[500],
    colorSuccess: colors.success.main,
    colorWarning: colors.warning.main,
    colorError: colors.error.main,
    colorInfo: colors.info.main,
    colorBgContainer: colors.background.light,
    colorBgElevated: colors.surface.light,
    colorBgLayout: colors.background.light,
    colorBgSpotlight: colors.surface.light,
    colorBgMask: 'rgba(0, 0, 0, 0.45)',
    colorBorder: colors.border.light,
    colorBorderSecondary: colors.neutral[200],
    colorFill: colors.neutral[100],
    colorFillSecondary: colors.neutral[50],
    colorFillTertiary: colors.neutral[50],
    colorFillQuaternary: colors.neutral[50],
    colorText: colors.text.primary.light,
    colorTextSecondary: colors.text.secondary.light,
    colorTextTertiary: colors.text.disabled.light,
    colorTextQuaternary: colors.text.disabled.light,
    colorTextPlaceholder: colors.text.disabled.light,
    colorTextDisabled: colors.text.disabled.light,
    colorTextHeading: colors.text.primary.light,
    colorTextDescription: colors.text.secondary.light,
    colorTextLabel: colors.text.secondary.light,
    colorTextBase: colors.text.primary.light,
    colorBgTextHover: colors.neutral[100],
    colorBgTextActive: colors.neutral[200],
    colorLink: colors.primary[500],
    colorLinkHover: colors.primary[600],
    colorLinkActive: colors.primary[700],
    colorHighlight: colors.error.main,

    // Typography
    fontFamily: typography.fontFamily.primary,
    fontFamilyCode: typography.fontFamily.mono,
    fontSize: parseInt(typography.fontSize.base),
    fontSizeSM: parseInt(typography.fontSize.sm),
    fontSizeLG: parseInt(typography.fontSize.lg),
    fontSizeXL: parseInt(typography.fontSize.xl),
    fontSizeHeading1: parseInt(typography.fontSize['5xl']),
    fontSizeHeading2: parseInt(typography.fontSize['4xl']),
    fontSizeHeading3: parseInt(typography.fontSize['3xl']),
    fontSizeHeading4: parseInt(typography.fontSize['2xl']),
    fontSizeHeading5: parseInt(typography.fontSize.xl),
    lineHeight: typography.lineHeight.normal,
    lineHeightLG: typography.lineHeight.relaxed,
    lineHeightSM: typography.lineHeight.tight,
    lineHeightHeading1: typography.variants.h1.lineHeight,
    lineHeightHeading2: typography.variants.h2.lineHeight,
    lineHeightHeading3: typography.variants.h3.lineHeight,
    lineHeightHeading4: typography.variants.h4.lineHeight,
    lineHeightHeading5: typography.variants.h5.lineHeight,

    // Spacing
    borderRadius: parseInt(spacing.borderRadius.base),
    borderRadiusLG: parseInt(spacing.borderRadius.lg),
    borderRadiusSM: parseInt(spacing.borderRadius.sm),
    borderRadiusXS: parseInt(spacing.borderRadius.sm),
    borderRadiusOuter: parseInt(spacing.borderRadius.base),
    padding: parseInt(spacing.component.padding.md.split(' ')[0]),
    paddingLG: parseInt(spacing.component.padding.lg.split(' ')[0]),
    paddingSM: parseInt(spacing.component.padding.sm.split(' ')[0]),
    paddingXS: parseInt(spacing.component.padding.xs.split(' ')[0]),
    paddingXXS: parseInt(spacing.xs),
    margin: parseInt(spacing.component.margin.md),
    marginLG: parseInt(spacing.component.margin.lg),
    marginSM: parseInt(spacing.component.margin.sm),
    marginXS: parseInt(spacing.component.margin.xs),
    marginXXS: parseInt(spacing.xs),
    controlHeight: 32,
    controlHeightLG: 40,
    controlHeightSM: 24,
    controlHeightXS: 16,

    // Motion
    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
    motionEaseOut: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    motionEaseInBack: 'cubic-bezier(0.6, -0.28, 0.735, 0.045)',
    motionEaseOutBack: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',

    // Wireframe
    wireframe: false,
  },
  components: {
    Button: {
      borderRadius: parseInt(spacing.borderRadius.base),
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      fontSize: parseInt(typography.variants.button.fontSize),
      fontWeight: typography.variants.button.fontWeight,
      lineHeight: typography.variants.button.lineHeight,
      boxShadow: shadows.component.button.default,
      boxShadowSecondary: shadows.component.button.hover,
    },
    Card: {
      borderRadius: parseInt(spacing.borderRadius.lg),
      boxShadow: shadows.component.card.default,
      boxShadowTertiary: shadows.component.card.hover,
      paddingLG: parseInt(spacing.lg),
      padding: parseInt(spacing.md),
      paddingSM: parseInt(spacing.sm),
    },
    Input: {
      borderRadius: parseInt(spacing.borderRadius.base),
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      fontSize: parseInt(typography.fontSize.base),
      lineHeight: typography.lineHeight.normal,
    },
    Modal: {
      borderRadius: parseInt(spacing.borderRadius.lg),
      boxShadow: shadows.component.modal,
      paddingLG: parseInt(spacing.lg),
      padding: parseInt(spacing.md),
      paddingSM: parseInt(spacing.sm),
    },
    Select: {
      borderRadius: parseInt(spacing.borderRadius.base),
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      fontSize: parseInt(typography.fontSize.base),
      lineHeight: typography.lineHeight.normal,
    },
    Table: {
      borderRadius: parseInt(spacing.borderRadius.base),
      headerBg: colors.surface.light,
      headerColor: colors.text.primary.light,
      headerSplitColor: colors.border.light,
      rowHoverBg: colors.neutral[50],
      borderColor: colors.border.light,
    },
    Typography: {
      titleMarginBottom: parseInt(spacing.sm),
      titleMarginTop: 0,
      colorTextHeading: colors.text.primary.light,
      colorText: colors.text.primary.light,
      colorTextDescription: colors.text.secondary.light,
    },
  },
};
