version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo npm install -g pnpm && pnpm install --frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Type check
          command: pnpm run check

  build-and-push:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
      - run:
          name: Build and Push Docker image
          environment:
            SERVICE_NAME: www-joymify
          command: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker build -t ghcr.io/montionugera/$SERVICE_NAME:$CIRCLE_SHA1 .
            docker tag ghcr.io/montionugera/$SERVICE_NAME:$CIRCLE_SHA1 ghcr.io/montionugera/$SERVICE_NAME:latest
            docker push ghcr.io/montionugera/$SERVICE_NAME:$CIRCLE_SHA1
            docker push ghcr.io/montionugera/$SERVICE_NAME:latest

  deploy-to-cluster:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod u+x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Deploy Code
          command: |
            chmod u+x ./scripts/ci-deploy.sh
            ./scripts/ci-deploy.sh

workflows:
  version: 2
  ci-cd-pipeline:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - deploy-to-cluster:
          requires:
            - build-and-push
          filters:
            branches:
              only: main
